routes/web.php
<?php
Auth::routes();

Route::get('/complete-registration', 'Auth\RegisterController@completeRegistration');

Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');

/**
 * Public Routes
 */
//The route to the home page on
//the site
Route::get('/', function () {
    return view('welcome');
});


////The route to the profile page on the
////site
//Route::get('/profile', function () {
//    return view('profile', [
//        'articles' => App\Article::latest()->get()
//    ]);
//});
//
//Route::get('/instaFeed', function () {
//    return view('instaFeed');
//});



//The routes for the Articles from the
//Article database
Route::resource('article', 'ArticleController');


//The routes for the Grades from the
//Grade database
Route::resource('grade', 'GradeController');


Route::get('/home', 'HomeController@index')
    ->name('home')
    ->middleware('auth');

app/Grade.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    protected $fillable = ['Course', 'EC'];


    public function insert($EC)
    {
        $this->score = $EC;
        $this->save();
        $this->pass();
    }

    public function pass()
    {
        if ($this->EC === $this->score) {
            $this->passed = true;
            $this->save();
        }
    }

    public function assignment()
    {
        return $this->hasMany(Assignment::class);
    }
}

app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Assignment;
use App\Grade;
use Illuminate\Http\Request;

class GradeController extends Controller
{
    //Show every grade on a dedicated grade page
    public function index()
    {
        $grade = Grade::latest()->get();

        return view('grade.index', ['grade' => $grade]);
    }

    //This function shows the assignments to the page from the
    //Assignment database
    public function show($id)
    {
        $grade = Grade::where('id', $id)->firstOrFail();
        return view('dashboard.show', ['details' => $grade->details, 'grade' => $grade]);
    }

    //Here you can create a new grade in the
    //Grade Database
    public function create()
    {
        //
    }


//Edit an existing article within the
//Article database
    public function edit(Grade $grade)
    {
        return view('grade.edit', ['grade' => $grade]);
    }

    //Save the edited grade in the
    //Grade database
    public function update(Grade $grade)
    {
       //dd(request());
        $grade->update($this->validateGrade());

        return redirect('/grade' . $grade->Id);

    }

    //Give parameters which every grade should have in the
    //Grade database
    protected function validateGrade()
    {
       return request()->validate([
            'Course' => 'required',
            'EC' => 'required',
        ]);
    }
}

resources/views/grade/edit.blade.php
@extends('layout.layout')

@section('content')

    <header class="textShadow">Edit</header>

    <form method="POST" action="/grade/{{ $grade->id }}">
        @csrf
        @method('PUT')

        <table>
            <tr>
                <th>Course</th>
                <th>EC</th>
            </tr>
            <tr>
                <label class="label" for="course"></label>

                <td>
                    <input class="input" type="text" name="course" id="course" placeholder="{{ $grade->course }}">
                </td>

                <label class="label" for="EC"></label>

                <td>
                    <input class="input" type="text" name="EC" id="EC" placeholder="{{ $grade->EC }}">
                </td>
            </tr>
        </table>






@endsection

resources/views/grade/index.blade.php
@extends('layout.layout')

@section('content')

    <header class="textShadow">Studiemonitor</header>

    <h1>Mijn vakken</h1>
    <table class='monitor'>
        <tr>
            <th>Cursus</th>

            <th>EC</th>

        </tr>
        @foreach($grade as $grade)
            <tr>
                <td>
                    <a href="{{ route('grade.show', $grade) }}">
                        {{$grade->course}}
                    </a>
                </td>

                <td>
                    <a href="{{ route('grade.show', $grade) }}">
                        {{$grade->EC}}
                    </a>
                </td>


            </tr>

        @endforeach
    </table>




@endsection

resources/views/grade/show.blade.php
@extends('layout.layout')

@section('content')

    <h1>{{$assignment->test}}</h1>
    <table>
        <tr>

            <th>Weging(%)</th>
            <th>EC</th>
            <th>score</th>
            <th>passed</th>
        </tr>
        <tr>
            <td> {{$assignment->weighting}}</td>
            <td> {{$assignment->EC}}</td>
            <td> {{$assignment->score}}</td>
            <td>{{$assignment->passed}}</td>
        </tr>
    </table>
@endsection